version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    # networks:
    #   - shopping_network

  backend:
    container_name: backend_app
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/shopping"
    # networks:
    #   - shopping_network

  frontend:
    container_name: frontend_app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    # networks:
    #   - shopping_network

volumes:
  mongo_data:
# networks:
#   shopping_network:
#     driver: bridge
